// src/config/permissions.js
export const permissions = {
  admin: {
    chatbot: { view: true },
    dashboard: { view: true, edit: true },
    hrMaster: { view: true },
    show: { view: true, edit: true },
    employeeMaster: { view: true, edit: true, delete: true },
    departmentMaster: { view: true, edit: true },
    shiftTime: { view: true, edit: true },
    grouproster: { view: true, edit: true },
    rosterCalendar: { view: true },
    shiftOvertimeRates: { view: true, edit: true },
    resignation: { view: true, edit: true },
    termination: { view: true, edit: true },
    userManagement: { view: true, add: true, edit: true, delete: true },
    accessControl: { view: true, edit: true },
    laborManagement: { view: true, edit: true },
    allowanceDeduction: { view: true },
    createNewAllowance: { view: true, edit: true },
    createNewDeduction: { view: true, edit: true },
    loans: { view: true },
    viewLoans: { view: true, edit: true },
    employeeLoan: { view: true, edit: true },
    loanApprovals: { view: true, approve: true },
    salaryProcess: { view: true },
    SalaryProcessPage: { view: true, edit: true },
    SalaryPage: { view: true },
    timeAttendance: { view: true },
    TimeCard: { view: true, edit: true },
    Overtime: { view: true, edit: true },
    lateEarlyApproval: { view: true, approve: true },
    timeCardApproval: { view: true, approve: true },
    timeCardAuditReport: { view: true },
    deletedTimeCardReport: { view: true },
    monthlyLateDeduction: { view: true, edit: true },
    excessLateReview: { view: true, edit: true },
    leaveMaster: { view: true, edit: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },
    employeeLeaveBalance: { view: true, edit: true },
    noPayManagement: { view: true, edit: true },
    advanceApprovals: { view: true, approve: true },
    weeklyOffManagement: { view: true, approve: true },
    medicalClaims: { view: true, approve: true },
    companyNotices: { view: true, add: true, delete: true },
    pendingPayments: { view: true, edit: true },
    leavecalendar: { view: true },
    reports: { view: true },
    timecardReports: { view: true },
    singleEntryReport: { view: true },
    attendanceReport: { view: true },
    absentReport: { view: true },
    shiftHoursReport: { view: true },
    monthlyWorkingHoursReport: { view: true },
    monthlyOtHoursReport: { view: true },
    contractAttendanceReport: { view: true },
    dailyOtHoursReport: { view: true },
    utilities: { view: true },
    // pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    taskApproval: { view: true, approve: true },
    myKPIs: { view: true },
    employeeEvaluation: { view: true, edit: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageExams: { view: true, edit: true },
    manageCourses: { view: true, edit: true },
    myProgress: { view: true },
    lmsUserStats: { view: true },
    accounting: { view: true },
    accountingDashboard: { view: true },
    customer: { view: true, edit: true },
    center: { view: true, edit: true },
    chartOfAccounts: { view: true, edit: true },
    accountList: { view: true, edit: true },
    supplierEnterBill: { view: true, edit: true },
    payment: { view: true, edit: true },
    advancePayment: { view: true, edit: true },
    makeDeposit: { view: true, edit: true },
    receipt: { view: true, edit: true },
    createUtilityBill: { view: true, edit: true },
    utilityBillPayment: { view: true, edit: true },
    journalEntry: { view: true, edit: true },
    pettyCash: { view: true, edit: true },
    cheque: { view: true, edit: true },
    bankReconciliation: { view: true, edit: true },
    transactions: { view: true, edit: true },
    transactionsList: { view: true, edit: true },
    salesOrder: { view: true, edit: true },
    salesReturn: { view: true, edit: true },
    grn: { view: true, edit: true },
    purchaseReturn: { view: true, edit: true },
    purchaseOrder: { view: true, edit: true },
    stockTransfer: { view: true, edit: true },
    stockVerification: { view: true, edit: true },
    ledger: { view: true },
    trialBalance: { view: true },
    incomeStatement: { view: true },
    balanceSheet: { view: true },
    cashFlowStatement: { view: true },
    invoices: { view: true, edit: true },
    expenses: { view: true, edit: true },
    financeReports: { view: true },
    accountingReports: { view: true },
    accountingSettings: { view: true, edit: true },
    usersAndRoles: { view: true, edit: true },
    PerformanceAppraisal: { view: true, edit: true },
    doubleEntry: { view: true, edit: true },
    supplier: { view: true, edit: true },
    product: { view: true, edit: true },
    inventory: { view: true, edit: true },
    productList: { view: true, edit: true },
    discountLevel: { view: true, edit: true },
    productType: { view: true, edit: true },
    pendingApprovals: { view: true, edit: true },
    leaveSettings: { view: true, edit: true },
    nopayWorkingDays: { view: true, edit: true },
    supervisorLeaveApproval: { view: true, approve: true },
    midShiftBreaks: { view: true, edit: true },

    allowancesReport: { view: true },

    // permissions map / roles file
createNewBonus: { view: true, create: true, update: true, delete: true },
dinnerAllowance: { view: true, edit: true, approve: true },
  },
  hr: {
    chatbot: { view: true },
    dashboard: { view: true, edit: true },
    hrMaster: { view: true },
    show: { view: true, edit: true },
    employeeMaster: { view: true, edit: true, delete: true },
    departmentMaster: { view: true, edit: true },
    shiftTime: { view: true, edit: true },
    grouproster: { view: true, edit: true },
    rosterCalendar: { view: true },
    shiftOvertimeRates: { view: true, edit: true },
    resignation: { view: true, edit: true },
    termination: { view: true, edit: true },
    userManagement: { view: true, edit: true, delete: true },
    laborManagement: { view: true, edit: true },
    allowanceDeduction: { view: true },
    createNewAllowance: { view: true, edit: true },
    createNewDeduction: { view: true, edit: true },
    loans: { view: true },
    viewLoans: { view: true, edit: true },
    employeeLoan: { view: true, edit: true },
    loanApprovals: { view: true, approve: true },
    salaryProcess: { view: true },
    SalaryProcessPage: { view: true, edit: true },
    SalaryPage: { view: true },
    timeAttendance: { view: true },
    TimeCard: { view: true, edit: true },
    Overtime: { view: true, edit: true },
    lateEarlyApproval: { view: true, approve: true },
    timeCardApproval: { view: true, approve: true },
    timeCardAuditReport: { view: true },
    deletedTimeCardReport: { view: true },
    monthlyLateDeduction: { view: true, edit: true },
    excessLateReview: { view: true, edit: true },
    leaveMaster: { view: true, edit: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },
    employeeLeaveBalance: { view: true, edit: true },
    noPayManagement: { view: true, edit: true },
    advanceApprovals: { view: true, approve: true },
    weeklyOffManagement: { view: true, approve: true },
    medicalClaims: { view: true, approve: true },
    companyNotices: { view: true, add: true, delete: true },
    pendingPayments: { view: true, edit: true },
    leavecalendar: { view: true },
    reports: { view: true },
    timecardReports: { view: true },
    singleEntryReport: { view: true },
    attendanceReport: { view: true },
    absentReport: { view: true },
    shiftHoursReport: { view: true },
    monthlyWorkingHoursReport: { view: true },
    monthlyOtHoursReport: { view: true },
    contractAttendanceReport: { view: true },
    dailyOtHoursReport: { view: true },
    utilities: { view: true },
    // pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    taskApproval: { view: true, approve: true },
    myKPIs: { view: true },
    employeeEvaluation: { view: true, edit: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageExams: { view: true, edit: true },
    manageCourses: { view: true, edit: true },
    myProgress: { view: true },
    lmsUserStats: { view: true },
    accounting: { view: true },
    accountingDashboard: { view: true },
    chartOfAccounts: { view: true, edit: true },
    transactions: { view: true, edit: true },
    transactionsList: { view: true, edit: true },
    salesOrder: { view: true, edit: true },
    salesReturn: { view: true, edit: true },
    grn: { view: true, edit: true },
    purchaseReturn: { view: true, edit: true },
    purchaseOrder: { view: true, edit: true },
    stockTransfer: { view: true, edit: true },
    stockVerification: { view: true, edit: true },
    ledger: { view: true },
    trialBalance: { view: true },
    incomeStatement: { view: true },
    balanceSheet: { view: true },
    cashFlowStatement: { view: true },
    invoices: { view: true, edit: true },
    expenses: { view: true, edit: true },
    accountingReports: { view: true },
    accountingSettings: { view: true, edit: true },
    usersAndRoles: { view: true, edit: true },
    PerformanceAppraisal: { view: true, edit: true },
    inventory: { view: true, edit: true },
    masterFiles: { view: true, edit: true },
    productList: { view: true, edit: true },
    discountLevel: { view: true, edit: true },
    leaveSettings: { view: true, edit: true },
    nopayWorkingDays: { view: true, edit: true },
    dinnerAllowance: { view: true, edit: true, approve: true },
     
    allowancesReport: { view: true },
    // permissions map / roles file
createNewBonus: { view: true, create: true, update: true, delete: true },
supervisorLeaveApproval: { view: true, approve: true },

  },
  supervisor: {
    chatbot: { view: true },
    dashboard: { view: true },
    hrMaster: { view: true },
    show: { view: true },
    employeeMaster: { view: true },
    departmentMaster: { view: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },

    supervisorLeaveApproval: { view: true, approve: true },
    leaveMaster: { view: true },
    leavecalendar: { view: true },
    reports: { view: true },
    timeCardApproval: { view: true, approve: true },
    weeklyOffManagement: { view: true, approve: true },
    medicalClaims: { view: true, approve: true },
    companyNotices: { view: true, add: true, delete: true },
    pendingPayments: { view: true, edit: true },
    timeCardAuditReport: { view: true },
    deletedTimeCardReport: { view: true },
    monthlyWorkingHoursReport: { view: true },
    monthlyOtHoursReport: { view: true },
    contractAttendanceReport: { view: true },
    dailyOtHoursReport: { view: true },
    // pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    myKPIs: { view: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageExams: { view: true, edit: true },
    manageCourses: { view: true, edit: true },
    myProgress: { view: true },
    lmsUserStats: { view: true },
    accounting: { view: true },
    accountingDashboard: { view: true },
   

    midShiftBreaks: { view: true, edit: true },
    transactions: { view: true },
    customer: { view: true, edit: true },
    center: { view: true, edit: true },
  product: { view: true, edit: true },
    chartOfAccounts: { view: true, edit: true },
    accountList: { view: true, edit: true },
    supplierEnterBill: { view: true, edit: true },
    payment: { view: true, edit: true },
    advancePayment: { view: true, edit: true },
    makeDeposit: { view: true, edit: true },
    receipt: { view: true, edit: true },
    createUtilityBill: { view: true, edit: true },
    utilityBillPayment: { view: true, edit: true },
    journalEntry: { view: true, edit: true },
    pettyCash: { view: true, edit: true },
    cheque: { view: true, edit: true },
    bankReconciliation: { view: true, edit: true },
 
    transactionsList: { view: true, edit: true },
    salesOrder: { view: true, edit: true },
    salesReturn: { view: true, edit: true },
    grn: { view: true, edit: true },
    purchaseReturn: { view: true, edit: true },
    purchaseOrder: { view: true, edit: true },
    stockTransfer: { view: true, edit: true },
    stockVerification: { view: true, edit: true },
    ledger: { view: true },
    trialBalance: { view: true },
    incomeStatement: { view: true },
    balanceSheet: { view: true },
    cashFlowStatement: { view: true },
    invoices: { view: true },
    expenses: { view: true },
    accountingReports: { view: true },
    inventory: { view: true, edit: true },
    // attendanceReport: { view: true },
    
    allowancesReport: { view: true },
    // permissions map / roles file
createNewBonus: { view: true, create: true, update: true, delete: true },
dinnerAllowance: { view: true, edit: true, approve: true },
  },
  user: {
    chatbot: { view: true },
    dashboard: { view: true },
    hrMaster: { view: true },
    show: { view: true },
    leaveMaster: { view: true, edit: true },
    leavecalendar: { view: true },
    myKPIs: { view: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageCourses: { view: true },
    manageExams: { view: true },
    myProgress: { view: true },
    accounting: { view: true },
    accountingDashboard: { view: true },
    // pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    
    inventory: { view: true },
    product: { view: true },

    // permissions map / roles file
createNewBonus: { view: true, create: true, update: true, delete: true }
  },
  employee: {
    employeePortal: { view: true },
  },
};
